const CapabilityActionTypes = {
  SET_CAPABILITIES: "SET_CAPABILITIES",
  GET_CAPABILITY: "GET_CAPABILITY",
  CLEAR_CAPABILITY: "CLEAR_CAPABILITY",
  ADD_CAPABILITY: "ADD_CAPABILITY",
  UPDATE_CAPABILITY: "UPDATE_CAPABILITY",
  DELETE_CAPABILITY: "DELETE_CAPABILITY",
  ERROR_CAPABILITY: "ERROR_CAPABILITY",
  CLEAR_ERROR: "CLEAR_ERROR"
}

export default CapabilityActionTypes;